### ISSUE TITLE
IOError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by sammcj** [hlamer/cpp2python#2]
Trying to convert: http://hg.linux-ha.org/glue/raw-file/9da0680bc9c0/lib/plugins/stonith/rcd_serial.c

```
samm-mbp ~/Desktop/plugin % ./cpp2python.py rcd_serial.c
Traceback (most recent call last):
  File "./cpp2python.py", line 299, in <module>
    process_file(sys.argv[1])
  File "./cpp2python.py", line 276, in process_file
    file.truncate(0)
IOError: [Errno 22] Invalid argument
```

**Comment by andreikop** [comment]
Fixed indirectly.
This code has been removed.
